CREATE TABLE users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Role TINYINT DEFAULT 0;
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Categories (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Image VARCHAR(255),
    Name VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL,
    Description MEDIUMTEXT,
    Status TINYINT DEFAULT 0,
    Popular TINYINT DEFAULT 0,
    Meta_Title VARCHAR(255),
    Meta_Description MEDIUMTEXT,
    Meta_Keywords VARCHAR(255),
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Products (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CategoryID INTEGER NOT NULL,
  Name VARCHAR(255) NOT NULL,
  Slug VARCHAR(255) NOT NULL,
  Small_Description MEDIUMTEXT,
  Description MEDIUMTEXT NOT NULL,
  Original_Price DECIMAL(10,2) NOT NULL,
  Selling_Price DECIMAL(10,2) NOT NULL,
  Image VARCHAR(255) NOT NULL,
  Quantity INTEGER NOT NULL,
  Status TINYINT,
  Trending TINYINT,
  Meta_Title VARCHAR(255),
  Meta_Keywords MEDIUMTEXT,
  Meta_Description MEDIUMTEXT,
  Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
  
);