CREATE TABLE users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Role TINYINT DEFAULT 0;
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Categories (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Image VARCHAR(255),
    Name VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL,
    Description TEXT,
    Status TINYINT DEFAULT 0,
    Popular TINYINT DEFAULT 0,
    Meta_Title VARCHAR(255),
    Meta_Description TEXT,
    Meta_Keywords VARCHAR(255),
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP
);
